// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLEl9bEPZRMqRFmXcJejA8j2Pb_Y53jeU',
    appId: '1:425344845833:web:062c50afa1c4bbafa1d0d8',
    messagingSenderId: '425344845833',
    projectId: 'project2-df745',
    authDomain: 'project2-df745.firebaseapp.com',
    databaseURL: 'https://project2-df745-default-rtdb.firebaseio.com',
    storageBucket: 'project2-df745.firebasestorage.app',
    measurementId: 'G-V8W62BQMZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArT2EMql17aRY6AJRDnN7LeDaQM78ZZs',
    appId: '1:425344845833:android:7a57447ce9e7a348a1d0d8',
    messagingSenderId: '425344845833',
    projectId: 'project2-df745',
    databaseURL: 'https://project2-df745-default-rtdb.firebaseio.com',
    storageBucket: 'project2-df745.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDPFy4j9sfODQcdX9A60M342eeS_NWGU',
    appId: '1:425344845833:ios:3fa7e4dbada0d147a1d0d8',
    messagingSenderId: '425344845833',
    projectId: 'project2-df745',
    databaseURL: 'https://project2-df745-default-rtdb.firebaseio.com',
    storageBucket: 'project2-df745.firebasestorage.app',
    iosBundleId: 'com.example.phoneAuth',
  );
}
